#!/bin/bash

echo "🚨 DEPLOY URGENTE - Correção Loop Infinito"
echo "========================================"

echo ""
echo "📋 EXECUTE ESTES COMANDOS NO SERVIDOR AWS:"
echo ""
echo "# 1. Navegar para o diretório do projeto"
echo "cd /var/www/novo-site-santos-cleaning"
echo ""
echo "# 2. Puxar as correções do GitHub"
echo "git pull origin main"
echo ""
echo "# 3. Verificar se a correção foi aplicada"
echo "grep -n 'useMemo.*frequencyMultipliers' frontend/src/components/PriceCalculator.js"
echo ""
echo "# 4. Fazer build de produção"
echo "cd frontend && npm run build && cd .."
echo ""
echo "# 5. Backup do build atual (precaução)"
echo "sudo cp -r /var/www/santos-cleaning/frontend/build /tmp/backup-build-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "# 6. Limpar build antigo e copiar novo"
echo "sudo rm -rf /var/www/santos-cleaning/frontend/build/*"
echo "sudo cp -r frontend/build/* /var/www/santos-cleaning/frontend/build/"
echo ""
echo "# 7. Reiniciar serviços"
echo "sudo systemctl reload nginx"
echo "pm2 restart all"
echo ""
echo "# 8. Verificar se hash mudou (deve ser diferente de main.d053da47.js)"
echo "curl -s http://localhost | grep -o 'main\.[a-f0-9]*\.js' | head -1"
echo ""
echo "# 9. Testar o site externamente"
echo "curl -s http://santoscsolutions.com | grep -o 'main\.[a-f0-9]*\.js' | head -1"
echo ""
echo "🎯 OBJETIVO: O hash JS deve mudar e a calculadora parar de piscar!"
echo ""
echo "⚠️  Se houver problemas, o backup está em /tmp/backup-build-*" 