name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build production
      run: |
        cd frontend
        npm run build
        
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 54.67.60.88
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /var/www/santos-cleaning || cd /var/www/novo-site-santos-cleaning
          git pull origin main
          cd frontend && npm install --omit=dev
          sudo systemctl restart nginx
          pm2 restart all || echo "PM2 não configurado"
          echo "Deploy concluído $(date)"
